version: 2.1
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["9f:9a:09:f9:b9:77:46:c3:5a:4e:38:38:35:16:9f:6d"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory.txt main.yml
workflows:
  provision:
    jobs:
      - create_infrastructure:
          name: create_infrastructure
      - configure_infrastructure:
          name: configure_infrastructure
          requires: ['create_infrastructure']
